[project]
name = "api"
version = "0.1.0"
description = "FastAPI backend service"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "uvicorn>=0.40.0",
]

[dependency-groups]

